config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#home'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
    collection do
      get 'filter'
      get 'recommendations'
    end
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :ingredient_id, :cocktail_id, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all.order(name: :asc)
    @search = params["search"]
    if @search.present?
      @name = @search["name"]
      @cocktails = Cocktail.where("name ILIKE ?", "%#{@name}%")
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  def filter
    @ingredient = Ingredient.find_by(name: params[:ingredient])
    @cocktail = @ingredient.cocktails
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    # get data from form
    @dose = Dose.new(dose_params)
    #assign cocktail to dose
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end


  private
  def dose_params
    params.require(:dose).permit(:description,:ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/filter.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1502819126416-d387f86d47a1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80);">
  <div class="container">
    <h1>Find 🥃 <%= @ingredient.name %></h1>
  </div>
</div>
<div class="container">
  <div class="row my-3">
    <div class="col-xs-12 col-sm-8 offset-sm-2 text-white text-decoration-none">
      <div class="filter-cards">
        <% @ingredient.cocktails.each do |cocktail|%>
          <div class="filter-item" style="padding:20px;"><%= link_to cocktail.name, cocktail %></div>
        <% end%>å
      </div>
    </div>
  </div>
</div>

app/views/cocktails/home.html.erb
<!-- banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);">
  <div class="container">
    <h1>Find 🍷🥂🥃 for 👱🏼‍♀️👩🏼‍🦰🧑🏽 night✨</h1>
    <p>It's beginning to look a lot like cocktails🌹</p>
    <%= simple_form_for :search, url: cocktails_path, method: "GET", html: { class: 'form-inline' } do |f| %>
      <%= f.input :name, input_html: {value: ""} %>
      <%= f.submit "Search", class: "btn btn-dark" %>
    <% end %>
  </div>
</div>
<!-- card-category -->
<div class="container">
  <div class="row my-3">
    <div class="col-xs-12 col-sm-6">
      <div class="card-category text-white text-decoration-none" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1567850174684-a9e79e49ee50?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80)">
        Recommendations
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="card-category text-white text-decoration-none" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1539112373701-6fc43d90f569?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
        <%= link_to "Gin", filter_cocktails_path(ingredient: 'Gin')%>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 text-white text-decoration-none">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1552215147-ebe5751c9eba?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80)">
        <%= link_to "Vodka", filter_cocktails_path(ingredient: 'Vodka')%>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 text-white text-decoration-none">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1522128483605-23607c944cbb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1649&q=80)">
        <%= link_to "Tequila", filter_cocktails_path(ingredient: 'Tequila')%>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 text-white text-decoration-none">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1529264978834-666a0e99f884?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80)">
        <%= link_to "Whiskey", filter_cocktails_path(ingredient: 'Whiskey')%>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 text-white text-decoration-none">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1570629557357-45c6767e0140?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80)">
        <%= link_to "All", cocktails_path%>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 text-white text-decoration-none">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1551024709-8f23befc6f87?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1425&q=80)">
        <%= link_to 'Add new Cocktail🍹', new_cocktail_path %>
      </div>
    </div>
  </div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1462539405390-d0bdb635c7d1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1393&q=80);">
  <div class="container">
    <h1>Find All🥃 </h1>
  </div>
  <%= simple_form_for :search, url: cocktails_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%= f.input :name, input_html: {value: ""} %>
    <%= f.submit "Search", class: "btn btn-dark" %>
  <% end %>
</div>
<div class="container">
  <div class="row my-3">
    <div class="filter-cards col-sm-8 offset-sm-2">
      <% @cocktails.each do |cocktail|%>
        <div class="filter-item">
          <ul style="list-style-type:none;">
            <li style="list-style-type:none;"><%=cocktail.name%> |   <%= link_to 'Show', cocktail %></li>
            <% cocktail.doses.each do |dose| %>
              <li> <%= dose.description%> - <%= link_to dose.ingredient.name, filter_cocktails_path(ingredient: dose.ingredient.name)%>  </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);">
  <div class="container">
    <h1>Add new cocktails</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 offset-sm-2 my-2">
      <%= simple_form_for(@cocktail) do |f| %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
        </div>
        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/recommendations.html.erb
<h1>recommendations.html.erb</h1>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1529604278261-8bfcdb00a7b9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80);">
  <div class="container">
    <h1>Discover more about  <%= @cocktail.name%>🥂</h1>
    <h5><%= @cocktail.preparation%></h5>
  </div>
</div>
<div class="card-product">
  <%= @cocktail.photo.attached? ? (cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill) : (image_tag 'cocktail.jpg', height: 200, width: 300) %>
  <div class="card-product-infos">
    <% if @cocktail.doses.any? %>
      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li>
            <%= dose.description %> | <%= link_to dose.ingredient.name, filter_cocktails_path(ingredient: dose.ingredient.name) %>   |  <%= link_to dose_path(dose) , method: :delete, data: {confirm: "Are you sure??"} do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No doses yet</p>
    <% end %>
  </div>
</div>
<%= link_to "Add a dose", new_cocktail_dose_path(@cocktail)  %>

app/views/doses/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);">
  <div class="container">
    <h1>Add new dose</h1>
  </div>
</div>
<div class="container">
  <div class="row my-3">
    <div class="col-xs-12 col-sm-8 offset-sm-2">
      <h3>Add new Dose to <%= @cocktail.name %> </h3>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <div class="form-inputs">
          <%= f.input :description %>
          <%= f.association :ingredient %>
        </div>
        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="link">
    <p>Have 🥂 with Jasmine🌹</p>
    <ul>
      <li>
        <a href="#">
          <i class="fab fa-fw fa-facebook-f"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fab fa-fw fa-instagram"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fab fa-fw fa-twitter"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fab fa-fw fa-github"></i>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-glass-martini-alt"></i>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  </div>
</div>